# Generated by Django 5.0.2 on 2024-03-07 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_publication_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('direction', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='publication',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name_of_product',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.CreateModel(
            name='SalePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.location')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='salePlace',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Api.saleplace'),
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
