# Generated by Django 5.0.2 on 2024-03-09 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_location_remove_product_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='salePlace',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='salePlace', serialize=False, to='Api.saleplace'),
        ),
        migrations.AlterField(
            model_name='saleplace',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='Api.location'),
        ),
    ]
